// Code generated by "stringer -type=ComponentType"; DO NOT EDIT.

package components

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Temperature-0]
	_ = x[Effort-1]
	_ = x[Power-2]
	_ = x[Flow-3]
}

const _ComponentType_name = "TemperatureEffortPowerFlow"

var _ComponentType_index = [...]uint8{0, 11, 17, 22, 26}

func (i ComponentType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ComponentType_index)-1 {
		return "ComponentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentType_name[_ComponentType_index[idx]:_ComponentType_index[idx+1]]
}
