// Code generated by "stringer -type=Status utils/types.go"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Healthy-0]
	_ = x[Warning-1]
	_ = x[Critical-2]
	_ = x[Offline-3]
}

const _Status_name = "HealthyWarningCriticalOffline"

var _Status_index = [...]uint8{0, 7, 14, 22, 29}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
