// Code generated by "stringer -type=SubsystemType utils/types.go"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Power-0]
	_ = x[Cooling-1]
	_ = x[Hvac-2]
}

const _SubsystemType_name = "PowerCoolingMachine"

var _SubsystemType_index = [...]uint8{0, 5, 12, 19}

func (i SubsystemType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SubsystemType_index)-1 {
		return "SubsystemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SubsystemType_name[_SubsystemType_index[idx]:_SubsystemType_index[idx+1]]
}
